target-version = "py311"
unsafe-fixes = true
preview = true

[format]
line-ending = "lf"
preview = true

[lint]
select = ["ALL"]
ignore = [
    "D",
    "CPY",
    "PLR2004", # [magic-value-comparison]
    "S101", # [assert]

    # Recommended to avoid when using Ruff Formatter
    "W191", # [tab-indentation]
    "E111", # [indentation-with-invalid-multiple]
    "E114", # [indentation-with-invalid-multiple-comment]
    "E117", # [over-indented]
    "D206", # [indent-with-spaces]
    "D300", # [triple-single-quotes]
    "Q000", # [bad-quotes-inline-string]
    "Q001", # [bad-quotes-multiline-string]
    "Q002", # [bad-quotes-docstring]
    "Q003", # [avoidable-escaped-quote]
    "COM812", # [missing-trailing-comma]
    "COM819", # [prohibited-trailing-comma]
    "ISC001", # [single-line-implicit-string-concatenation]
    "ISC002", # [multi-line-implicit-string-concatenation]
]

[lint.flake8-type-checking]
quote-annotations = true

[lint.isort]
split-on-trailing-comma = false
